### ISSUE TITLE
RPM lint warning in dependency {users-0.7.0 via update-ssh-keys-0.3.0): call to setgroups before setuid

### ISSUE THREAD

**Issue by jfkw** [coreos/afterburn#118]
# Bug #

When building coreos-3.0.1, rpmlint reports call to `setgroups` before `setuid`.

This appears to be in crate `users-0.7.0`, a dependency of direct dependency crate `update-ssh-keys-0.3.0`. Some changes in this area have been integrated in users-0.8.0, currently researching whether those eliminate the warning.

The warning may not indicate an actual problem, but it would be helpful to eliminate the warning if a fix is available through a newer version of a dependency.

## Operating System Version ##

`OpenSUSE Tumbleweed  20181018-0 x86_64`

## coreos-metadata Version ##

`coreos-metadata-3.0.1`

## Environment ##

Open Build Service (OBS) `osc build` local.

Local RPM lint warning at build time, no error running executable. Not running on any cloud provider.

## Expected Behavior ##

Build executable that passes standard RPM lint checks.

## Actual Behavior ##

```
RPMLINT report:
===============
coreos-metadata.x86_64:
W: missing-call-to-setgroups-before-setuid /usr/bin/coreos-metadata
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

## Reproduction Steps ##

  1. Routine osc build to build local package
  2. RPM lint warning above displayed.

## Other Information ##

Occurrences of `setgroups` are all in crate `libc-0.2.43`.
Occurrences of `setuid` are in crate `libc-0.2.43` and crate `users-0.7.0`.

The rpmlint warning is not specific to a particular call site. Dependency crate `users-0.7.0` has potentially relevant code here: https://github.com/ogham/rust-users/blob/v0.7.0/src/switch.rs#L25

Commits between crate `users-0.7.0` (pinned) and crate `users-0.8.0` (available) suggest some work may have been done in this area:  https://github.com/ogham/rust-users/compare/v0.7.0...master
I will test a build with crate `users-0.8.0` and report back here.

**Comment by lucab** [comment]
Thanks for the report. I think this ticket is actually covering `update-ssh-keys`, but I'm fine handling this here.

The warning is related to `switch_user_group` in the `users` crate (all versions): https://github.com/ogham/rust-users/blob/15af1576e40fd3e5592b918de353df6a976c42c4/src/switch.rs#L134-L143

We are calling that in `update-ssh-keys`: https://github.com/coreos/update-ssh-keys/blob/v0.3.0/src/lib.rs#L108

In our specific case I think this is not a security bug. We are calling that method in order to align user/group on file creation only, not to drop privileges for the process (those are reset when the guard value is dropped at the end of the function).

I think it is still worth to report as bug against https://github.com/ogham/rust-users. @jfkw do you want to do that yourself? If/when fixed, we will pick up the new dependency both here an in update-ssh-keys.

**Comment by jfkw** [comment]
@lucab Yes, thanks, I'll report the issue at rust-users.

**Comment by bgilbert** [comment]
I'm not seeing the rpmlint warning with Afterburn 5.3.0, so I'll assume that recent rust-users (we're using 0.11) has fixed this.  Closing, but feel free to reopen if you're still seeing this.
