### ISSUE TITLE
docs: mention platform naming skew

### ISSUE THREAD

**Issue by lucab** [coreos/afterburn#251]
Afterburn usually follows Ignition platform naming convention, in order to auto-detect the platform.

However there are several platforms where the metadata component is only optional. On those platforms, in case of failures, Afterburn cannot distinguish a known-good state (i.e. this infra lacks the metadata component) from a failed state (i.e. network or logic error).

As such, Afterburn knows about the following platform which are more specific than the Ignition ones, cannot be auto-detected, and require user-provided hints (as cmdline flags):
 * `cloudstack-metadata`
 *  `cloudstack-configdrive`
 * `openstack-metadata`
 * `vagrant-virtualbox`

**Comment by lucab** [comment]
This follows up to @cgwalters's doubt from https://github.com/openshift/machine-config-operator/pull/964#issuecomment-511036266.

**Comment by bgilbert** [comment]
`openstack-metadata` has since been consolidated into a platform ID `openstack` that does match Ignition.  `vagrant-virtualbox` has been removed, and https://github.com/coreos/afterburn/issues/856 tracks consolidation of the CloudStack providers into a `cloudstack` one.  Closing this in favor of fixing CloudStack to use the Ignition platform ID.
