### ISSUE TITLE
dracut: run hostname service on aliyun

### ISSUE THREAD

**Issue by yunhui-del** [coreos/afterburn#482]
AliCloud havn't DHCP for set hostname when firstboot, could you add condition for aliyun in afterburn-hostname.service ?
@lucab

**Comment by lucab** [comment]
Thanks for the report. The fix for this is indeed a small tweak to the hostname service conditions. However last time we were doing cloud-enablement work for `aliyun` I don't remember noticing the hostname missing from DHCP.

@xuanyunhui which region and instance type are you using?

Before proceeding I'll try to get back access to an account myself and check what's going on, possibly in the next couple of weeks.

**Comment by yunhui-del** [comment]
Thank for your response. We are use **ecs.g6.4xlarge** in **region cn-beijing-h**, is this issues also with any other instance type in any other region. I confirm aliyun haven't DHCP in VPC with employee of aliyun.

**Comment by robertvolkmann** [comment]
@lucab I also run in this issue and created a pull request for it.
