### ISSUE TITLE
Appending DNS to IPCFG

### ISSUE THREAD

**Issue by pk-vungle** [coreos/afterburn#517]
# Feature Request #
guestinfo.afterburn.initrd.network-kargs should be able to read DNS nameservers for VMware environments.

According to dracut, this should work:
ip=client-IP:[peer]:gateway-IP:netmask:client_hostname<interface:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[dns1][:dns2]]

## Environment ##
VMware version 15

What hardware/cloud provider/hypervisor is being used to run Afterburn?
I'm using this for deploying RHCOS on VMware

## Other Information ##
this works as expected
IPCFG="ip=10.20.30.42::10.20.30.254:255.255.255.0:mynode01:ens192:off" 

I have tested below settings and all won't work:
IPCFG="ip=10.20.30.42::10.20.30.254:255.255.255.0:mynode01:ens192:off:dns ip"
IPCFG="ip=10.20.30.42::10.20.30.254:255.255.255.0:mynode01:ens192:off:dns ip:dns ip"
IPCFG="ip=10.20.30.42::10.20.30.254:255.255.255.0:mynode01:ens192:off nameserver=dns ip"

**Comment by lucab** [comment]
Thanks for the report. Afterburn does not process the argument itself, it only propagates that for other software to consume in the initramfs.

I think you are facing either one of:
 * a wrong syntax (I think the manpage is actually telling you to use `ip=<...>:ens192:off:8.8.8.8`)
 * NetworkManager not correctly consuming the `ip=`

As such, I'm closing this bug here, but feel free to continue your investigation and contact your OCP support channel for further assistance.
If you indeed confirm this is a bug in parsing `ip=` parameters, the proper place to report that is a bugzilla ticket against NetworkManager for RHEL8.
